default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dk-rhino_development
test:
  <<: *default
  database: dk-rhino_test

production:
  reconnect: true
  adapter: postgresql
  database: rhino
  encoding: utf-8
  pool: 16
  username: rhino
  password: <%= ENV['DATABASE_PASSWORD'] %>
